### ISSUE TITLE
Bind Keys to Version and Purpose

### ISSUE THREAD

**Issue by paragonie-security** [nbaars/paseto4j#12]
https://github.com/nbaars/paseto4j/blob/16b8fd40253d88562f6e15b10f6b6075606b7ef1/version2/src/main/java/org/paseto4j/version2/PasetoLocal.java#L94

https://github.com/nbaars/paseto4j/blob/16b8fd40253d88562f6e15b10f6b6075606b7ef1/version2/src/main/java/org/paseto4j/version2/PasetoPublic.java#L72

See https://github.com/paseto-standard/paseto-spec/blob/master/docs/02-Implementation-Guide/03-Algorithm-Lucidity.md

Right now, byte arrays are accepted by this API. There's no mechanism to prevent a user from using a v2 public key as a v2 local key.

**Comment by nbaars** [comment]
@paragonie-security: implemented the spec and pushed a new release to Maven Central, see https://github.com/nbaars/paseto4j/releases/tag/0.0.31
