### ISSUE TITLE
V1 Public Signed Token by paseto.js not able be verified by JAVA Public V1 verify

### ISSUE THREAD

**Issue by nickfai936** [nbaars/paseto4j#3]
Hi, I am new to paseto. I recently using the paseto (javascript) and was able to sign and verify with my own private and public keys but when other people who use JAVA paseto4j to verify the signed token and it will prompts invalid signature error.
The strange thing is, I was able to verify the signed token by JAVA paseto4j with the same Javascript paseto codes.

**Comment by nbaars** [comment]
@nickfai936 can you give an example? As far as I can tell from the issue you were able to use both sides, but other people were not? Might be an issue with the other side processing your public key?
