### ISSUE TITLE
Add V4

### ISSUE THREAD

**Issue by nbaars** [nbaars/paseto4j#32]

**Comment by jhult** [comment]
I have a branch where ~50-75% of this is done.

I seem to be blocked on XChaCha20 not yet being implemented:

- Bouncy Castle issue: https://github.com/bcgit/bc-java/issues/631
- JDK issue: https://bugs.openjdk.org/browse/JDK-8256529

**Comment by nbaars** [comment]
@jhult super thanks! For `XChaCha20Poly1305` we can use `libsodium` bindings the same as used in version 2 of the protocol implementation. Do you have a PR?

**Comment by nbaars** [comment]
thanks to @untoldwind version 4 has been added
