### ISSUE TITLE
cant make token if i run my project as a jar

### ISSUE THREAD

**Issue by alphacellbox** [nbaars/paseto4j#91]
its like issue that people have here
https://github.com/spring-projects/spring-boot/issues/28837
problem is with version 3
if u didnt undrestand what is wrong then read this:
i am making a spring boot app...there is this line in my app that work good if i run my app in intelij " Security.addProvider(new BouncyCastleProvider()); Cipher aes = Cipher.getInstance("AES/CTR/NoPadding", "BC");" but if i make a jar from my app and then try to run it then it throw this exception "Caused by: java.lang.SecurityException: JCE cannot authenticate the provider BC at java.base/javax.crypto.Cipher.getInstance(Cipher.java:723) ~[na:na] at java.base/javax.crypto.Cipher.getInstance(Cipher.java:643) ~[na:na] " how to make my code work fine when it is a jar?
by the way i am using springboot 3.0.6 and jdk 19 ... u used BouncyCastleProvider in your lib in CryptoFunction.class encryptDecrypt method line 66
and i kinda tried  all dependency that i colud find here: https://mvnrepository.com/artifact/org.bouncycastle
with "provider" scope in pom.xml
and i tried this link too: https://stackoverflow.com/questions/13721579/jce-cannot-authenticate-the-provider-bc-in-java-swing-application  like put security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider in java.security file
or set crypto.policy to unlimited

**Comment by nbaars** [comment]
@alphacellbox I've read the thread in Spring projects, this is very unfortunate to say at least :-(

**Comment by nbaars** [comment]
@alphacellbox this is not directly an issue of this library. If you use BouncyCastle and a Oracle JDK it will fail with Spring Boot. You could use an OpenJDK as suggested in the Github issue.

Closing this issue as it is not related to this project directly. Feel free to reopen the issue if you think it is related to this project in particular.
